### ISSUE TITLE
generate error

### ISSUE THREAD

**Issue by zsy619** [Sammy-Colon/go-builder-pattern-boilerplate#1]
type LinkModel struct {
	Model *cms_domain.CmsLink     `json:"model" form:"model"`
	Album *attach_domain.SysAlbum `json:"album" from:"album"`
}
生成错误：
func (articleModel *ArticleModel) WithModel *cms_domain.CmsArticle `json:"model"(model *cms_domain.CmsArticle `json:"model" form:"model"`) *ArticleModel {
	articleModel.Model *cms_domain.CmsArticle `json:"model" = model *cms_domain.CmsArticle `json:"model";
	return articleModel;
}

func (articleModel *ArticleModel) WithAlbum *attach_domain.SysAlbum `json:"album"(album *attach_domain.SysAlbum `json:"album" from:"album"`) *ArticleModel {
	articleModel.Album *attach_domain.SysAlbum `json:"album" = album *attach_domain.SysAlbum `json:"album";
	return articleModel;
}

func (articleModel *ArticleModel) Build() ArticleModel {
	return *articleModel;
}

func DefaultArticleModel() *ArticleModel {
	return &ArticleModel{}
}

**Comment by Sammy-Colon** [comment]
Hi @zsy619,
thank you for opening this issue. This bug is fixed in `v1.0.6` - you can update the extension version in VSC/VSCodium to use the newest version!
